services:
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: "always"
    ports:
      # 5000 is used by Control Center on macOS
      - "5001:80"
      - "25:25"
      - "143:143"
    networks:
      - "idlewalk"
    volumes:
      - smtp4dev-data:/smtp4dev
volumes:
  smtp4dev-data:
