services:
  db:
    image: postgres:17
    restart: "always"
    environment:
      POSTGRES_DB: idlewalk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - idlewalk
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "idlewalk", "-U", "postgres"]
      interval: "10s"
      timeout: "30s"
      retries: 5
      start_period: "20s"

networks:
  idlewalk: {}

volumes:
  postgres_data:
